export const AuthURL = {
    Dashboard: 'dashboard',
    Setting: 'setting',
    Profile: 'profile',
    Members: 'members',
    MembersCreate: 'member-create',
    Companies:'companies',
    CompaniesCreate:'company-create',
    News:'news',
    Cvs:'cvs',
    Services:'services',
    ServicesCreate:'service-create',
    DashboardCom: 'dashboard-company',
    ProfileCom:'profile-company',
    ComService:'company-service',
    ListNews:'list-news',
    AddNews:'add-news',
    NewCv:'news-cv',
    LisCv:'list-cv',
    InfoCom:'info-company',
    Manalocation:'manager-location',
    ManaCareer:'manager-career',
    SearchCv:'search-cv',
    ListSaveCV:'list-save-cvs'

};
